<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[hello python]]>
    </line>
    <line>
      <![CDATA[hello selenium]]>
    </line>
    <line>
      <![CDATA[hello java]]>
    </line>
  </reporter-output>
  <suite started-at="2021-04-01T09:33:38 IST" name="Suite" finished-at="2021-04-01T09:33:38 IST" duration-ms="255">
    <groups>
    </groups>
    <test started-at="2021-04-01T09:33:38 IST" name="Test" finished-at="2021-04-01T09:33:38 IST" duration-ms="255">
      <class name="demo123.Test0">
        <test-method signature="demo()[pri:0, instance:demo123.Test0@2118cddf]" started-at="2021-04-01T09:33:38 IST" name="demo" finished-at="2021-04-01T09:33:38 IST" duration-ms="8" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hello java]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo -->
      </class> <!-- demo123.Test0 -->
      <class name="demo123.Test2">
        <test-method signature="demo()[pri:0, instance:demo123.Test2@57250572]" started-at="2021-04-01T09:33:38 IST" name="demo" finished-at="2021-04-01T09:33:38 IST" duration-ms="39" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hello python]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo -->
      </class> <!-- demo123.Test2 -->
      <class name="demo123.Test1">
        <test-method signature="demo()[pri:0, instance:demo123.Test1@5609159b]" started-at="2021-04-01T09:33:38 IST" name="demo" finished-at="2021-04-01T09:33:38 IST" duration-ms="6" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hello selenium]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo -->
      </class> <!-- demo123.Test1 -->
      <class name="demo123.Test3">
        <test-method signature="demo()[pri:0, instance:demo123.Test3@17a7f733]" started-at="2021-04-01T09:33:38 IST" name="demo" finished-at="2021-04-01T09:33:38 IST" duration-ms="22" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [selenium] but found [appium]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [selenium] but found [appium]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at demo123.Test3.demo(Test3.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo -->
      </class> <!-- demo123.Test3 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
